blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
]

prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                         # 추가 1
from django.conf.urls.static import static
from prj.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('shop/', include('shop.urls'), name='shop'),
    path('blog/', include('blog.urls'), name='blog'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:                                       # 추가 2
    import debug_toolbar                                 # 추가 2
    urlpatterns += [                                     # 추가 2
        path('__debug__/', include(debug_toolbar.urls)), # 추가 2
    ]                                                    # 추가 2

shop/urls.py
from django.urls import path, register_converter
from shop import views
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('', views.item_list, name='item_list'),                        # 조회
    path('view/<int:pk>/', views.item_detail, name='item_detail'),      # 조회
    path('new/', views.item_new, name='item_new'),                      # 등록
    path('remove/<int:pk>/', views.item_remove, name='item_remove'),    # 삭제
    path('edit/<int:pk>/', views.item_edit, name='item_edit'),          # 수정
]

prj/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from blog.models import *
from shop.models import *



class FirstMixin(TemplateView):
    model = Post
    def get_context_data(self, **kwargs):
        pst = super(FirstMixin, self).get_context_data(**kwargs)
        pst['posts'] = Post.objects.all().order_by('-updated_at')[:3]
        return pst
    
class SecondMixin(TemplateView):
    model = Item
    def get_context_data(self, **kwargs):
        ctx = super(SecondMixin, self).get_context_data(**kwargs)
        ctx['items'] = Item.objects.all().order_by('-price')[:3]
        return ctx
    
    
class HomeView(FirstMixin, SecondMixin):
    # model = Post, Item
    template_name = 'home.html'
    
    
    
    
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

prj/templates/base.html
<!DOCTYPE html>     <!--HTML5 규약을 준수하는 파일-->
<html lang="ko">    <!--언어는 한국어로 지정--><!---->

<head>              <!--페이지 타이틀과 css 파일 2개를 연결-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% block title %}5조 과제{% endblock %}</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="robots" content="all,follow">
{% load staticfiles %}  <!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
<!--스타일시트 css/base.css 작성이 필요함-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />   <!--추가적인 css파일 불러오고 싶으면 사용. 현재는 비어있음-->
{#<link rel="shortcut icon" href="{% static 'img/favi.ico' %}">#}
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">


</head>

<body>              <!--바디 영역은 4 영역(헤더/메뉴/콘텐츠/풋터)으로 구성-->

<!--Navbar -->
<div class="container mt-4">
    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark indigo">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" class="logo"/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link waves-effect waves-light" href="{% url 'home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect waves-light" href="{% url 'blog:post_list' %}">BLOG</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect waves-light" href="{% url 'shop:item_list' %}">SHOP</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect waves-light" href="{% url 'admin:index' %}">ADMIN</a>
                    </li>
                </ul>
                <span class="navbar-text">
                {#유저정보 부분#}
                    {% if user.is_active %}
                    <h4 class="welcome">
                        <strong>{% firstof user.get_short_name user.get_username %}</strong> 님 /
                                <a href="{% url 'password_change' %}">비밀번호 변경</a> /  {#  #}
                                <a href="{% url 'logout' %}">로그아웃</a>  {#  #}
                    </h4>
                    {% else %}
                    <h4 class="welcome">익명의 사용자 님  /
                                <a href="{% url 'login' %}">로그인</a> /
                                <a href="{% url 'register' %}">회원가입</a>
                    </h4>
                    {% endif %}
                </span>
            </div>
        </nav>
    </header>

</div>

    {% block content %}
    {% endblock %}   <!--블록 태그로 콘텐츠 영역 정의 -->


    {% block footer %}
	<section id="footer">
		<div class="container">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
            <a href="#"><h6 class="text-uppercase mb-4 font-weight-bold">scroll up</h6></a>
                <p>&nbsp;</p>
            </div>
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Threewheel Company</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Email</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>CS CENTER</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Number</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Operating Time</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Public Holiday</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>BANK INFO</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Bank Info</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Account Number</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Account Holder</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p>&nbsp;</p>
					<p><u><a href="http://www.hywoman.ac.kr/">Hywoman University SmartIT3</a></u> Graduation work</p>
					<p class="h6">© 2019 Copyright:<a class="text-green ml-2" href="http://www.hywoman.ac.kr/" target="_blank">threewheel company</a></p>
				</div>
				</hr>
			</div>
		</div>
	</section>
    {% endblock %}
</body>
</html>

prj/templates/home.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}5조 과제{% endblock %}    <!--title 블록 재정의-->

<!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
{% load staticfiles %}
<!--extrastyle 블록을 재정의하여 추가적으로 home.css 연결-->
{% block extrastyle %}{% static "css/home.css" %}
{% endblock %}
{% block content %}
    <!--header부분-->
<header>
    <div class="carousel fade-carousel slide">
    <!-- Overlay -->
        <div class="overlay"></div>
    <!-- Wrapper for slides -->
        <div class="carousel-inner">
        <div class="item slides active">
        <div class="slide-1"></div>
        <div class="hero">
            <h2>Weak things united become strong.</h2>
            <button class="btn btn-hero btn-lg col-10 col-lg-2 col-md-4 col-sm-5 col-lg-offset-4" role="button">QUIZ</button> &nbsp;
            <button class="btn btn-hero btn-lg col-10 col-lg-2 col-md-4 col-sm-5" role="button">GAME</button>
        </div>
    </div>
  </div>
</div>
</header>
<!--content 블록 재정의-->
<div id="content_home" class="mx-auto">     <!--content_home 영역 정의-->
    <div class="text-center">
        <br/><br/>
    <section>
        <h2 style="display:inline;">
            세바퀴
        </h2> <br/><br/>
            <b>세바퀴를 소개합니다.</b> <br/><br/>
        <span class="line"></span> <br/>

        <div class="main2 row justify-content-center">
            <div class="col-lg-3 col-12 col-md-4 col-sm-4 order-1">
            <img src="{% static 'img/main1.png' %}" class="main1"/>
            <p>잊고 있었던 상식 얻기 <br/> <b>"상식을 얻자"</b></p><br/>
            <button type="button" class="btn btn-outline-success">퀴즈</button>
            </div>
            <div class="col-lg-3 col-12 col-md-4 col-sm-4 order-2">
            <img src="{% static 'img/main2.png' %}" class="main1"/>
            <p>작물 키우기로 다양한 보상 받기<br/> <b>"씨앗을 얻자"</b></p>
                <br/>
            <button type="button" class="btn btn-outline-success">게임</button>
            </div>
            <div class="col-lg-3 col-12 col-md-4 col-sm-4 order-3">
            <img src="{% static 'img/main3.png' %}" class="main1"/>
            <p>퀴즈 참여로 쉬운 기부하기 <br/> <b>"기부에 참여하자"</b></p><br/>
            <button type="button" class="btn btn-outline-success">기부</button>
            </div>
        </div>
    </section>

</div>
</div>
    {# 회전목마 - carousel효과 #}
    <section>
        <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width: 100%">
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{% static 'img/Green.PNG' %}" class="d-block w-100">
                </div>

                <div class="carousel-item">
                  <img src="{% static 'img/uni.PNG' %}" class="d-block w-100">
                </div>

                <div class="carousel-item">
                  <img src="{% static 'img/world.PNG' %}" class="d-block w-100">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-item" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-item" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>
    </section>
<div id="content_home" class="mx-auto">
<div class="text-center">
        <!--카드형식 부분-->
    <section>
        <h2>비싼 씨앗</h2><hr/> <br/>
        <div class="row justify-content-center">
            {% for item in items %}
            <div class="col-sm-9 col-8 col-md-4 mb-4">
              <div class="card shadow border-0 h-100"><a href="{% url 'shop:item_detail' item.id %}"><img src="{{ item.photo.url }}" alt="" class="card-img-top" ></a>
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'shop:item_detail' item.id %}" class="text-dark">{{ item.name }}</a></h5>
                    <p class="text card-text" style="font-size: 14px;">{{ item.price }}원</p>
                    <p class="mb-0"><a href="{% url 'shop:item_detail' item.id %}">상품 자세히 보기</a></p>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <br/><br/>
     <!--공지사항 부분-->
    <section>
        <div id="board">
            <h2>세바퀴 소식</h2><br/>
            <table id="applist" class="table col-12">
                {% for post in posts %}
                <tr>
                    <td><b>
                        {{ forloop.counter }}.
                        &nbsp;</b></td>
                    <td class="board_cnt"><a href="{% url 'blog:post_list'%}">{{post.title}}</a></td>
                    <td class="board_cnt d-lg-block d-md-block d-none"><a href="{% url 'blog:post_list'%}">{{post.short_content}}</a></td>
                    <td class="more"><a href="{% url 'blog:post_detail' post.id %}">
                        <svg class="lnr text-primary services-icon">
                        <use xlink:href="#lnr-chevron-right-circle"></use>
                        </svg></a>
                    </td>{# {% url 'blog:post_detail' ''%} #}
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
</div>
</div>

{% endblock content %}

prj/templates/layout.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <h1>threewheel</h1>


        <img src="{% static 'phd_shin.png' %}" alt="main logo image">
        <h1>threewheel site</h1>


    <hr/>
    No &copy;! <img src="http://www.pngmart.com/files/8/Copyleft-PNG-Transparent-Picture.png" height="42" width="42" style="margin-bottom: -5px" />2019. threewheel.

    {% block extra_body %}
        <script src="{% static 'main.js' %}"></script>
    {% endblock %} {# 자바스크립트 등을 위하여 #}


{% endblock content %}