prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                         # 추가 1
from django.conf.urls.static import static
from prj.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('shop/', include('shop.urls'), name='shop'),
    path('blog/', include('blog.urls'), name='blog'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:                                       # 추가 2
    import debug_toolbar                                 # 추가 2
    urlpatterns += [                                     # 추가 2
        path('__debug__/', include(debug_toolbar.urls)), # 추가 2
    ]                                                    # 추가 2

shop/urls.py
from django.urls import path, register_converter
from shop import views
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('', views.item_list, name='item_list'),                        # 조회
    path('view/<int:pk>/', views.item_detail, name='item_detail'),      # 조회
    path('new/', views.item_new, name='item_new'),                      # 등록
    path('remove/<int:pk>/', views.item_remove, name='item_remove'),    # 삭제
    path('edit/<int:pk>/', views.item_edit, name='item_edit'),          # 수정
]

shop/models.py
from django.db import models
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    photo = models.ImageField()  # blank=True 지정하지 않은 경우
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk': self.pk})

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView
from .models import Item
from .form import ItemForm


item_new = CreateView.as_view(model=Item, form_class=ItemForm)
item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)


def item_remove(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    return redirect('shop:item_list')


def item_list(request):
    items = Item.objects.all()
    # 키값이 'q'로 지정된 값이 없으면 None이 반환됨
    q = request.GET.get('q', '')  # 'q'로 지정된 값이 없으면 '' 반환
    if q:  # q가 널 아니면 qs에 filter 조건 추가
        items = items.filter(name__icontains=q)
    return render(request, 'shop/item_list.html', {
        'item_list': items,
        'q': q, })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html',
                  {'item': item})

shop/templates/shop/item_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    {{ block.super }}
<div style="margin: 0 auto; width: 85%;">
    <br/><br/><br/><br/>
    <a href="{% url 'shop:item_list' %}"><button type="button" class="btn btn-outline-success">상품 목록</button></a> <br/><br/>
    <form>
    <fieldset>
    <table class="table">
        <thead>
            <th>필드</th><th>내용</th>
        </thead>
        <tbody>
        <tr>
            <td width="15%">id:</td>
            <td>{{ item.id }}</td>
        </tr>
        <tr>
            <td>상품명:</td>
            <td>{{ item.name }}</td>
        </tr>
        <tr>
            <td>설명:</td>
            <td>
                {{ item.desc.strip }}
            </td>
        </tr>
        <tr>
            <td>가격:</td>
            <td>{{ item.price|intcomma }} 원
            </td>
        </tr>
        <tr>
            <td>사진:</td>
            <td>
                {% if item.photo %}<img src="{{ item.photo.url }}" style="height: 20vw"/>{% endif %}
            </td>
        </tr>
        <tr>
            <td>출시 여부:</td>
            <td>
                <input type="checkbox" name="item.is_published" value="1"
                       {% if item.is_published %}checked{% endif %} />
            </td>
        </tr>
        </tbody>
    </table>
    </fieldset>
    </form> <br/><br/>
    <a href="{% url 'shop:item_edit' item.pk %}"><button type="button" class="btn btn-outline-success">상품 수정</button></a>
    <a href="{% url 'shop:item_remove' item.pk %}"><button type="button" class="btn btn-outline-success">상품 삭제</button></a>
</div>

{% endblock content %}

shop/templates/shop/item_form.html
{% extends 'base.html' %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
{% endblock %}

{% block content %}
    {{ block.super }}<br/><br/><br/><br/>
    <div class="container">
        <div class="col-sm-12">
            {% if request.path == '/shop/new/' %}
                <h2>상품 등록</h2>
            {% elif request.path|slice:":11" == '/shop/edit/' %}
                <h2>상품 수정</h2>
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{ form.as_table }}
                </table>
                <input type="submit" value="저장하기" class="btn btn-outline-success" />
            </form>
        </div>
    </div>
{% endblock content %}

shop/templates/shop/item_form_old.html
{% extends 'base.html' %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="container">
        <div class="col-sm-12">
            {{ request.path }}
            {% if request.path == '/shop/new/' %}
                <h2>상품 등록</h2>
            {% elif request.path|slice:"5:11" == '/edit/' %}
                <h2>상품 수정</h2>
            {% endif %}

            {% if error_list %}
                <div class="alert alert-danger">
                    error_list: {{ error_list }}
                </div>
            {% endif %}

            {% if initial %}
                <div class="alert alert-info">
                    initial: {{ initial }}
                </div>
            {% endif %}

            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}

                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th>상품 이름</th>
                            <td>
                                <input type="text" name="name" value="{{ initial.name }}" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>상품 설명</th>
                            <td>
                                <textarea name="desc" class="form-control"
                                    cols="40" rows="10">{{ initial.desc }}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th>가격 (원)</th>
                            <td>
                                <input type="text" name="price" value="{{ initial.price }}" class="form-control" style="width:150px; text-align:right;"/>
                            </td>
                        </tr>
                        <tr>
                            <th>상품 사진</th>
                            <td>
                                {% if initial.photo %}<img src="{{ initial.photo.url }}"/>{% endif %}
                                <input type="file" name="photo"
                                       value="{{ initial.photo.url }}" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>출시 여부</th>
                            <td>
                                <input type="checkbox" name="is_published" value="1"
                                       {% if initial.is_published %}checked{% endif %} />
                            </td>
                        </tr>
                    </tbody>
                </table>

                <input type="submit" value="저장하기" class="btn btn-primary" />
            </form>

        </div>
    </div>
{% endblock content %}

shop/templates/shop/item_list.html
<!-- shop/templates/shop/item_list.html -->
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    {{ block.super }} <br/><br/><br/><br/>
<div style="margin: 0 auto; width: 85%;">
    <h4>상품 목록</h4>
    <hr>
    <form action="" method="GET">
        <input type="text" name="q" value="{{ q }}" class="form-control" style="width: 50%; display: inline;"/>
        <input type="submit" value="검색" class="btn btn-outline-success" style="margin-bottom: 6px; margin-left: 5px;"/>
    </form>
    <br/><br/>
    <table class="table">
        <thead>
            <th class="text-center">번호</th>
            <th class="text-center">사진</th>
            <th>이름</th>
            <th class="d-lg-table-cell d-md-table-cell d-sm-none d-none">설명</th>
            <th class="text-center">가격</th>

            <th class="d-lg-table-cell d-md-table-cell d-sm-none d-none">출시 여부</th>
            <th>수정</th>
            <th>삭제</th>
        </thead>
        <tbody>
            {% for item in item_list %}
            <tr style="background-color:
                {% ifchanged item.id %}
                    {% cycle 'white' '#eeeeee' %}
                {% else %}
                    'gray'
                {% endifchanged %}"
            >
                <td align="center"> {{ item.id }} </td>
                <td><img src="{{ item.photo.url }}" style="width: 80px; height: 70px; object-fit: cover;" > </td>
                <td>
                    <a href="{{ item.get_absolute_url }}">
                        {{ item.name }}
                    </a>
                </td>
                <td class="d-lg-table-cell d-md-table-cell d-sm-none d-none"> {{ item.desc|truncatechars:15 }} </td>
                <td align="right"> {{ item.price|intcomma }} 원</td>

                <td class="d-lg-table-cell d-md-table-cell d-sm-none d-none"><input type="checkbox" name="item.is_published" value="1"
                       {% if item.is_published %}checked{% endif %} />
                </td>
                <td>
                    <a href="{% url 'shop:item_edit' item.pk %}">
                        수정
                    </a>
                </td>
                <td>
                    <a href="{% url 'shop:item_remove' item.pk %}">
                        삭제
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> <br/><br/>

    <a href="{% url 'shop:item_new' %}"><button type="button" class="btn btn-outline-success">새 상품 등록</button></a>

</div>

{% endblock %}

shop/templates/shop/layout.html
<!-- shop/templates/shop/layout.html -->
{% extends '../layout.html' %}

{% load static %}

{% block title %}
    {{ block.super }} shop
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <img src="{% static 'shop/com_shin.png' %}" alt="shop logo image">
    <h2>shop in logistex site </h2>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script src="{% static 'shop/shop.js' %}"></script>
{% endblock %}